name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.os }} target on ${{ matrix.on }}
    runs-on: ${{ matrix.on }}
    strategy:
      fail-fast: false
      matrix:
        os: [ Linux, macOS, Windows ]
        on: [ ubuntu-24.04, macos-15, macos-14 ]
        exclude:
          - os: Linux
            on: macos-15
          - os: Linux
            on: macos-14
          - os: macOS
            on: ubuntu-24.04
    steps:
    - name: id
      id: id
      env:
        os_: ${{ matrix.os }}_
        _on_: ${{ matrix.os != runner.os && '_on_' || '' }}${{ matrix.os != runner.os && runner.os || '' }}
        cross_: ${{ matrix.os != runner.os && 'cross_' || '' }}${{ matrix.os != runner.os && matrix.os || '' }}
        _cross_: ${{ matrix.os != runner.os && '=cross_' || '' }}${{ matrix.os != runner.os && matrix.os || '' }}
        type: ${{ matrix.os == runner.os && 'native' || 'cross' }}
      run: |
        printf '%s\n' \
               "on_${{ runner.os }}=on_${{ runner.os }}" \
               "${{ matrix.os }}=${{ matrix.os }}" \
               ${{ env.cross_ }}${{ env._on_ }}${{ env._cross_ }}${{ env._on_ }} \
               "build=${{ matrix.os != runner.os && env.os_ || '' }}${{ matrix.on }}" \
               "${{ matrix.os }}_${{ runner.os }}=${{ env.type }}_${{ matrix.os }}" \
               "${{ env.type }}_${{ matrix.os }}=${{ env.type }}_${{ matrix.os }}" \
               "${{ env.type }}=${{ env.type }}" >> "$GITHUB_OUTPUT"

    - uses: actions/checkout@v4

    - name: Clone msvc-wine
      if: ${{ steps.id.outputs.cross_Windows }}
      uses: actions/checkout@v4
      with:
        repository: imaami/msvc-wine
        path: ${{ github.workspace }}/msvc-wine
        ref: msvc-17.13-10.0.26100-14.43.17.13

    - name: Configure build
      id: cfg
      env:
        build_type: ${{ steps.id.outputs.cross }}${{ steps.id.outputs.native }}
        cc: ${{ steps.id.outputs.on_macOS && 'clang' || 'clang-21' }}
        ccl: ${{ steps.id.outputs.cross_Windows_on_Linux && 'clang-cl-21' || '' }}
        baseflags: -std=gnu2${{ steps.id.outputs.on_macOS && 'x' || '3' }} -flto=full -O3 -Wall -Wextra -Wpedantic -Weverything -DNDEBUG=1
        archflags: ${{ ! steps.id.outputs.macOS && ' -fuse-ld=lld' || '' }}${{ steps.id.outputs.Linux && ' -march=x86-64-v3 -mtune=znver3' || '' }}
        ext: ${{ steps.id.outputs.Windows && '.exe' || '' }}
      run: |
        exe="dbs26-${{ env.cc }}${{ env.ext }}"
        ${{ env.ccl && 'exe_ccl=dbs26-' || '' }}${{ env.ccl }}${{ env.ccl && env.ext || '' }}
        printf '%s\n' \
               ${{ steps.id.outputs.cross_Windows && 'maybe_use_wine="set \$(command -v wine64 || command -v wine-stable || command -v wine || echo false) \"\$@\""' || '' }} \
               cc=${{ env.cc }} \
               ${{ env.ccl && 'ccl=' || '' }}${{ env.ccl }} \
               cflags="${{ env.baseflags }}${{ env.archflags }}" \
               exe="$exe" \
               ${{ env.ccl && 'exe_ccl=$exe_ccl' || '' }} \
               pkg=dbs26-${{ steps.id.outputs.build }} \
               src="args.c dbs26.c" >> "$GITHUB_OUTPUT"

        ${{ steps.id.outputs.cross_Windows && '
        echo "WINEDEBUG=-all" >> "$GITHUB_ENV"
        msvc_sdk="$GITHUB_WORKSPACE/msvc"
        printf "%s\n"                                 \
               msvc_cache="$GITHUB_WORKSPACE/cache"   \
               msvc_bin="$msvc_sdk/bin/x64"           \
               msvc_git="$GITHUB_WORKSPACE/msvc-wine" \
               msvc_sdk="$msvc_sdk" >> "$GITHUB_OUTPUT"
        ' || '' }}

        printf "%s\n" \
               build_dir="$GITHUB_WORKSPACE/build" \
               build_type="${{ env.build_type }}" >> "$GITHUB_OUTPUT"

    - name: Generate build
      id: f
      env:
        update_on_Linux: |
          echo "deb http://apt.llvm.org/noble/ llvm-toolchain-noble main" | \
          sudo tee /etc/apt/sources.list.d/apt.llvm.org.list > /dev/null
          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | \
          sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc > /dev/null
          sudo apt-get update -y
          sudo apt-get purge -y firefox snapd

        update_on_macOS: |
          brew update --quiet
          brew install --quiet bash

        cache_cross_Windows: |
          mkdir -p "$MSVC_CACHE"
          "$MSVC_GIT/vsdownload.py" --accept-license --architecture=x64 --host-arch=x64 --only-host=yes --preview --print-hashes --save-manifest > SHA256SUMS
          local manifest=$(ls -1tr | grep '\.manifest$' | tail -1) || true
          local version=$(jq -r '.info.productSemanticVersion' "$manifest")
          local hash=$(${{ steps.id.outputs.on_macOS && 'shasum' || 'sha1sum' }} SHA256SUMS)
          local k="msvc-$version" r
          echo "key=$k-${hash::40}" >> "$GITHUB_OUTPUT"
          {
            echo 'keys<<EOF'
            while [[ "$k" != "$r" ]]; do
              echo "$k"; r="$k"
              k="${k%?${k##*[0-9][.+-]}}"
            done
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"
          echo "manifest=$(realpath "$manifest")" >> "$GITHUB_OUTPUT"
          echo "path=${MSVC_CACHE#$GITHUB_WORKSPACE/}" >> "$GITHUB_OUTPUT"

        pre_depends_cross_Windows_on_Linux: |
          sudo apt-get install -y msitools winbind wine wine64 dos2unix
        pre_depends_cross_Windows_on_macOS: |
          brew install --quiet msitools wine-stable dos2unix

        depends_cross_Windows: |
          local OLD_CACHE=''
          if [[ "$cache_miss" ]]; then
            printf '\033[1;33mRe-caching MSVC SDK\033[m\n'
            if [[ -d "$MSVC_CACHE" ]]; then
              OLD_CACHE="$MSVC_CACHE.old"
              mv "$MSVC_CACHE" "$OLD_CACHE"
            fi
          else
            printf '\033[1;32mInstalling MSVC SDK\033[m\n'
          fi
          mkdir -p "$MSVC_CACHE" "$MSVC_SDK"
          "$MSVC_GIT/vsdownload.py" --accept-license --architecture=x64 --host-arch=x64 --only-host=yes --preview --manifest="$MANIFEST" --cache="$MSVC_CACHE"${OLD_CACHE:+ --migrate="$OLD_CACHE"} --dest="$MSVC_SDK"
          if [[ "$OLD_CACHE" && -d "$OLD_CACHE" ]]; then
            rm -rf "$OLD_CACHE"
          fi
          unset OLD_CACHE
          "$MSVC_GIT/install.sh" "$MSVC_SDK"

        post_depends_on_Linux: |
          sudo apt-get install -y clang clang-21 lld lld-21 llvm-21-linker-tools python3-pip
          python -m pip install ninja meson

        post_depends_on_macOS: |
          brew install --quiet coreutils gnu-sed llvm lld meson
          echo "$(brew --prefix)/opt/llvm/bin:$(brew --prefix)/opt/coreutils/libexec/gnubin:$(brew --prefix)/opt/gnu-sed/libexec/gnubin" >> "$GITHUB_PATH"
        post_depends_cross_Windows_on_macOS: |
          brew install --quiet binutils
          echo "$(brew --prefix)/opt/binutils/bin" >> "$GITHUB_PATH"

        pre_introspect_cross_Windows: |
          local msvc_version=$(dos2unix < "$MSVC_SDK/VC/Auxiliary/Build/Microsoft.VCToolsVersion.default.txt")
          local winsdk_version=$(dos2unix < "$MSVC_SDK/Windows Kits/10/SDKManifest.xml" \
          | grep -Eo 'PlatformIdentity *= *"[^"]+"' | grep -Eo '[0-9]+(\.[0-9]+)+')
          local arch=x64 base="Z:${MSVC_SDK//\//\\}"
          local vc="$base\\VC\\Tools\\MSVC\\$msvc_version"
          local sdk="$base\\Windows Kits\\10"
          local inc="$sdk\\Include\\$winsdk_version"
          local lib="$sdk\\Lib\\$winsdk_version"

          local INCLUDE="$vc\\include;$inc\\ucrt;$inc\\um;$inc\\shared;$inc\\winrt"
          local LIB="$vc\\lib\\$arch;$lib\\ucrt\\$arch;$lib\\um\\$arch"
          local WINEPATH="$vc\\bin\\Host$arch\\$arch"
          WINEPATH+=";$sdk\\bin\\$winsdk_version\\$arch"
          set -- $(command -v wine64 wine-stable wine 2>/dev/null || true)
          printf '%s\n'                       \
                 wine_exe="${1##*/}"          \
                 include="$INCLUDE"           \
                 lib="$LIB"                   \
                 msvc_version="$msvc_version" \
                 winepath="$WINEPATH"         \
                 winsdk_version="$winsdk_version" >> "$GITHUB_OUTPUT"

        introspect: |
          set +e
          uname -a
          printf -- '\n+---------+\n|compilers|\n+---------+\n'
          . .github/workflows/functions.bash
          get_compilers
          local -a cc_clang cc_gcc y
          local -A cc_v cc_x
          local _cc v x n
          for _cc in "${compilers[@]}"; do
            v=$("$_cc" --version 2>&1 | head -1)
            [[ "$v" ]] || continue
            printf -vx -- '%s\n'                                               \
              '#if defined __clang__'                                          \
              'y=(clang __clang_major__ __clang_minor__ __clang_patchlevel__)' \
              '#elif defined __GNUC__'                                         \
              'y=(gcc __GNUC__ __GNUC_MINOR__ __GNUC_PATCHLEVEL__)'            \
              '#else'                                                          \
              'continue'                                                       \
              '#endif'
            eval $("$_cc" -xc -E -P - <<< "$x")
            printf -vx -- '%d.%d.%d' ${y[*]:1:3}
            case ${y[0]} in
            clang) cc_clang+=("$_cc") ;;
            gcc)   cc_gcc+=("$_cc")   ;;
            *)     continue           ;;
            esac
            cc_x["$_cc"]="$x"
            cc_v["$_cc"]="$v"
          done
          n=$(printf '%s\n' "${cc_clang[@]}" "${cc_gcc[@]}" | wc -L)

          x="$(for _cc in "${cc_clang[@]}"; do
            printf "%s\t%-${n}s  %s\n" "${cc_x[$_cc]}" "$_cc" "${cc_v[$_cc]}"
          done | sort -V -r | cut -f2-)"
          echo "chosen_clang=${x%% *}" >> "$GITHUB_OUTPUT"
          sed -E 's,^([^ ]+)( +)([^ ].*)$,'$'\033[1;34m\\1\033[m\\2\033[36m\\3\033[m,' <<< "$x"

          x="$(for _cc in "${cc_gcc[@]}"; do
            printf "%s\t%-${n}s  %s\n" "${cc_x[$_cc]}" "$_cc" "${cc_v[$_cc]}"
          done | sort -V -r | cut -f2-)"
          echo "chosen_gcc=${x%% *}" >> "$GITHUB_OUTPUT"
          sed -E 's,^([^ ]+)( +)([^ ].*)$,'$'\033[1;32m\\1\033[m\\2\033[33m\\3\033[m,' <<< "$x"

        pre_compile: |
          mkdir -p "$BUILD_DIR"
        pre_compile_native_macOS: |
          local crossfile
          printf -v crossfile -- '%s = %s\n'             \
                 llvm_suffix "'${chosen_clang##*clang}'"
          printf '[constants]\n%s' "$crossfile" > "$GITHUB_WORKSPACE/ci.ini"
        pre_compile_cross_Windows: |
          local crossfile
          printf -v crossfile -- '%s = %s\n'             \
                 llvm_suffix "'${chosen_clang##*clang}'" \
                 msvc_sdk "'$MSVC_SDK'"                  \
                 msvc_version "'$msvc_version'"          \
                 wine_exe "[ '$wine_exe' ]"
          printf '[constants]\n%s' "$crossfile" > "$GITHUB_WORKSPACE/ci.ini"
          wineboot || true
          winecfg -v win11 || true
          wineserver -p || true
        compile_Linux: |
          CC="$chosen_clang" CC_LD=lld meson setup "$BUILD_DIR" "$GITHUB_WORKSPACE" \
                                       -Dm_arch=x86-64-v3 -Dm_tune=znver3 -Dstupid=true || {
            cat "$BUILD_DIR/meson-logs/meson-log.txt"
            false
          }
          meson compile -C "$BUILD_DIR" || {
            cat "$BUILD_DIR/meson-logs/meson-log.txt"
            false
          }
          local f
          for f in "$BUILD_DIR/dbs26"*; do
            [[ -f "$f" ]] || continue
            strip --strip-all "$f"
          done
        compile_native_macOS: |
          CC_FOR_BUILD="$chosen_clang" CC_LD_FOR_BUILD=lld           \
          meson setup "$BUILD_DIR" "$GITHUB_WORKSPACE" -Dstupid=true \
                --cross-file="$GITHUB_WORKSPACE"/{ci,llvm,macos,x86_64}.ini || {
            cat "$BUILD_DIR/meson-logs/meson-log.txt"
            false
          }
          meson compile -C "$BUILD_DIR" || {
            cat "$BUILD_DIR/meson-logs/meson-log.txt"
            false
          }
        compile_cross_Windows: |
          printf 'ci.ini:\n%s\nINCLUDE=%s\nLIB=%s\nWINEPATH=%s\n' \
                 "$(sed 's,^,  ,' "$GITHUB_WORKSPACE/ci.ini")"    \
                 "$INCLUDE" "$LIB" "$WINEPATH"

          meson setup "$BUILD_DIR" "$GITHUB_WORKSPACE" -Dstupid=true        \
                --cross-file="$GITHUB_WORKSPACE"/{ci,msvc,x86_64,wine}.ini || {
            cat "$BUILD_DIR/meson-logs/meson-log.txt"
            false
          }
          meson compile -C "$BUILD_DIR" || {
            cat "$BUILD_DIR/meson-logs/meson-log.txt"
            false
          }

          BIN="$MSVC_BIN" . "$MSVC_GIT/msvcenv-native.sh"
          export PATH="$MSVC_BIN:$PATH"
          "$chosen_clang" --target=$TARGET_TRIPLE $c_flags -o "$BUILD_DIR/${{ steps.cfg.outputs.exe }}" ${{ steps.cfg.outputs.src }}
        post_compile_cross_Windows_on_Linux: |
          "${{ steps.cfg.outputs.ccl }}" -nologo /TC /DNDEBUG=1 /Wall /O2 /Oi /GF /Zo- /MT /Fe: "$BUILD_DIR/${{ steps.cfg.outputs.exe_ccl }}" -fuse-ld=lld ${{ steps.cfg.outputs.src }}
        post_compile: |
          cat "$BUILD_DIR/compile_commands.json" | jq -C

        pre_validate: |
          try() {
            ${{ steps.cfg.outputs.maybe_use_wine }}
            "$@" -o -     | sha1sum       ; rm -f "$out"
            "$@" -o "$out"; sha1sum "$out"; rm -f "$out"
          }
          local f
        validate: |
          ${{ ! steps.id.outputs.native_macOS && '
            for f in ./dbs26*; do
              [[ -f "$f" ]] || continue
              try "$f"
            done
          ' || '' }}
        validate_native_macOS: |
          for f in ./dbs26*; do
            [[ -f "$f" ]] || continue
            try arch -arm64 "$f"  || true
            try arch -x86_64 "$f" || true
          done

        type: ${{ steps.cfg.outputs.build_type }}
        cross_on: |
          # <step>_cross_<target>_on_<runner>
          f="${x}_cross_${{ matrix.os }}_on_${{ runner.os }}"
          y="${!f}"
          [[ -z "${y// /}" ]] || {
            printf -vfn -- '%s\n%s' "$fn" "$y"
          }
      run: |
        gen() {
          local fn='' x f y
          for x in pre_$1 $1 post_$1; do
            # <step>_on_<runner>
            f="${x}_on_${{ runner.os }}"
            y="${!f}"
            [[ -z "${y// /}" ]] || {
              printf -vfn -- '%s\n%s' "$fn" "$y"
            }

            # <step>_<target>
            f="${x}_${{ matrix.os }}"
            y="${!f}"
            [[ -z "${y// /}" ]] || {
              printf -vfn -- '%s\n%s' "$fn" "$y"
            }

            # <step>_cross_<target>_on_<runner>
            ${{ steps.id.outputs.cross && env.cross_on || '' }}

            # <step>_<build_type>_<target>
            # (i.e. <step>_cross_<target> and <step>_native_<target>)
            f="${x}_${{ env.type }}_${{ matrix.os }}"
            y="${!f}"
            [[ -z "${y// /}" ]] || {
              printf -vfn -- '%s\n%s' "$fn" "$y"
            }

            # <step>_<build_type> (i.e. <step>_cross and <step>_native)
            f="${x}_${{ env.type }}"
            y="${!f}"
            [[ -z "${y// /}" ]] || {
              printf -vfn -- '%s\n%s' "$fn" "$y"
            }

            # <step>
            y="${!x}"
            [[ -z "${y// /}" ]] || {
              printf -vfn -- '%s\n%s' "$fn" "$y"
            }
          done
          x=($fn)
          y=${x[*]}
          [[ "${y// /}" ]] || return 0
          printf -vfn -- 'do_%s() {%s\n}\n' "$1" "$fn"
          unset -f "do_$1"
          eval "$fn"
          printf -vfn -- '%s\n' "$(declare -f "do_$1")"
          unset -f "do_$1"
          printf '%s' "$fn" | sed -E $'s/^/\| \033['"$2"$'m/;s/$/\033[m/'
          printf -vfn -- '%s%s\n' "$fn" "do_$1"
          printf '%s<<EOF\n%s\nEOF\n' "$1" "$fn" >> "$GITHUB_OUTPUT"
        }

        gen update      '1;32'
        gen cache       '1;35'
        gen depends     '1;36'
        gen introspect  '1;34'
        gen compile     '1;33'
        gen validate    '1;32'

    - name: Update system
      run: |
        ${{ steps.f.outputs.update }}

    - name: Prepare cache
      id: cache
      env:
        MSVC_CACHE: ${{ steps.cfg.outputs.msvc_cache }}
        MSVC_GIT: ${{ steps.cfg.outputs.msvc_git }}
        MSVC_SDK: ${{ steps.cfg.outputs.msvc_sdk }}
      run: |
        ${{ steps.f.outputs.cache }}

    - name: Cache MSVC SDK
      if: ${{ steps.id.outputs.cross_Windows }}
      id: cache-msvc
      uses: actions/cache@v4
      with:
        path: ${{ steps.cache.outputs.path }}
        key: ${{ steps.cache.outputs.key }}
        restore-keys: |
          ${{ steps.cache.outputs.keys }}

    - name: Install dependencies
      env:
        cache_miss: ${{ steps.id.outputs.cross_Windows && steps.cache-msvc.outputs.cache-hit != 'true' && '1' || '' }}
        MANIFEST: ${{ steps.cache.outputs.manifest }}
        MSVC_CACHE: ${{ steps.cfg.outputs.msvc_cache }}
        MSVC_GIT: ${{ steps.cfg.outputs.msvc_git }}
        MSVC_SDK: ${{ steps.cfg.outputs.msvc_sdk }}
      run: |
        ${{ steps.f.outputs.depends }}

    - name: Introspect
      id: introspect
      env:
        MSVC_SDK: ${{ steps.cfg.outputs.msvc_sdk }}
      run: |
        ${{ steps.f.outputs.introspect }}

    - name: Compile
      working-directory: ${{ github.workspace }}/src
      env:
        BUILD_DIR: ${{ steps.cfg.outputs.build_dir }}
        chosen_clang: ${{ steps.introspect.outputs.chosen_clang }}
        c_flags: ${{ steps.cfg.outputs.cflags }}
        MSVC_BIN: ${{ steps.cfg.outputs.msvc_bin }}
        MSVC_GIT: ${{ steps.cfg.outputs.msvc_git }}
        MSVC_SDK: ${{ steps.cfg.outputs.msvc_sdk }}
        INCLUDE: ${{ steps.introspect.outputs.include }}
        LIB: ${{ steps.introspect.outputs.lib }}
        LIBPATH: ${{ steps.introspect.outputs.lib }}
        WINEPATH: ${{ steps.introspect.outputs.winepath }}
        wine_exe: ${{ steps.introspect.outputs.wine_exe }}
        msvc_version: ${{ steps.introspect.outputs.msvc_version }}
        winsdk_version: ${{ steps.introspect.outputs.winsdk_version }}
      run: |
        ${{ steps.f.outputs.compile }}

    - name: Package
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.cfg.outputs.pkg }}
        path: |
          ${{ steps.cfg.outputs.build_dir }}/dbs26*
          !${{ steps.cfg.outputs.build_dir }}/*.p

    - name: Validate
      working-directory: ${{ steps.cfg.outputs.build_dir }}
      env:
        out: ${{ runner.temp }}/test.bin
      run: |
        ${{ steps.f.outputs.validate }}
