name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    shell: bash

env:
  __build_path: build
  __dest_path: dest
  __nproc: nproc
  __cc: clang-21
  __cflags: -std=gnu23 -flto=full -fuse-ld=lld -O3 -Wall -Wextra -Wpedantic -Weverything -DNDEBUG=1 -march=x86-64-v3 -mtune=znver3

jobs:
  build:
    name: ${{ matrix.os }}${{ matrix.os != matrix.on && ' target on ' || '' }}${{ matrix.os != matrix.on && matrix.on || '' }}
    runs-on: ${{ matrix.on == 'macOS' && 'macos-15' || 'ubuntu-24.04' }}
    strategy:
      matrix:
        os: [ Linux, macOS, Windows ]
        include:
          - os: Linux
            on: Linux
          - os: macOS
            on: macOS
          - os: Windows
            on: Linux
    env:
      project: dbs26
    steps:
    - name: Set build config
      id: cfg
      env:
        exe: ${{ env.project }}${{ matrix.os == 'Windows' && '.exe' || '' }}
        wine: ${{ matrix.os == 'Windows' && runner.os != 'Windows' && 'WINEDEBUG=-all wine64 ' || '' }}
        zip: ${{ env.project }}-${{ matrix.os }}
      run: |
        printf '%s=%s\n' \
               exe "$exe" ${{ matrix.os == 'Windows' && 'exe2 "cl-$exe" ' || '' }}\
               ${{ matrix.os == runner.os && 'native' || 'cross' }} ${{ matrix.os }} \
               wine "$wine" \
               zip "$zip" >> "$GITHUB_OUTPUT"
    - name: Install system updates
      env:
        Linux: |
          ${{ matrix.os == 'Windows' && 'sudo mkdir -pm755 /etc/apt/keyrings
          wget -qO- https://dl.winehq.org/wine-builds/winehq.key | \
          sudo gpg --dearmor -o /etc/apt/keyrings/winehq-archive.key -
          wget -qO- https://dl.winehq.org/wine-builds/ubuntu/dists/noble/winehq-noble.sources | \
          sudo tee /etc/apt/sources.list.d/winehq.sources
          sudo dpkg --add-architecture i386' || '' }}
          echo "deb http://apt.llvm.org/noble/ llvm-toolchain-noble main" | \
          sudo tee /etc/apt/sources.list.d/apt.llvm.org.list
          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | \
          sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
          sudo apt-get update
          sudo apt-get upgrade -y
        macOS: |
          set +e
          brew update
          brew upgrade
          brew install bash
      run: |
        ${{ runner.os == 'Linux' && env.Linux || '' }}
        ${{ runner.os == 'macOS' && env.macOS || '' }}
    - name: Set env variables
      id: env
      env:
        __msvc_path_Linux: ${{ matrix.os == 'Windows' && 'msvc' || '' }}
        __nproc_macOS: sysctl -n hw.logicalcpu
        __cc_macOS: clang
        __cflags_macOS: -std=gnu2x -flto=full -O3 -Wall -Wextra -Wpedantic -Weverything -DNDEBUG=1
        exe: ${{ steps.cfg.outputs.exe }}
        exe2: ${{ steps.cfg.outputs.exe2 }}
      run: |
        def() {
          set "$1" "${1}_${{ runner.os }}"
          if [[ "${!2}" ]]; then
            declare -g "$1=${!2//$'\n'/ }"
            echo "$1=${!1}" >> "$GITHUB_ENV"
          fi
        }

        def __cc
        def __cflags
        def __nproc
        ${{ steps.cfg.outputs.wine && 'def __msvc_path
        [[ "$__msvc_sdk_path" ]] || {
          __msvc_sdk_path="$__msvc_path/sdk"
          echo "__msvc_sdk_path=$__msvc_sdk_path" >> "$GITHUB_ENV"
        }
        [[ "$__msvc_dir"     ]] || __msvc_dir="$GITHUB_WORKSPACE/$__msvc_path"
        [[ "$__msvc_sdk_dir" ]] || __msvc_sdk_dir="$__msvc_dir/sdk"
        [[ "$__msvc_bin_dir" ]] || __msvc_bin_dir="$__msvc_sdk_dir/bin/x64"
        printf "%s=%s\n" \
               msvc_dir "$__msvc_dir" \
               msvc_sdk_dir "$__msvc_sdk_dir" \
               msvc_bin_dir "$__msvc_bin_dir" >> "$GITHUB_OUTPUT"
        ' || '' }}
        [[ "$__build_dir" ]] || __build_dir="$GITHUB_WORKSPACE/$__build_path"

        printf "%s=%s\n" \
               build_dir "$__build_dir" \
               built_exe "$__build_dir/$exe" \
               ${{ env.exe2 && 'built_exe2 "$__build_dir/$exe2" ' || '' }} >> "$GITHUB_OUTPUT"

    - uses: actions/checkout@v4

    - name: Clone msvc-wine
      if: ${{ steps.cfg.outputs.wine }}
      uses: actions/checkout@v4
      with:
        repository: mstorsjo/msvc-wine
        path: ${{ steps.env.outputs.msvc_dir }}
        ref: master

    - name: Install build dependencies
      env:
        msvc_dir: ${{ steps.env.outputs.msvc_dir }}
        msvc_sdk_dir: ${{ steps.env.outputs.msvc_sdk_dir }}
        msvc_bin_dir: ${{ steps.env.outputs.msvc_bin_dir }}
      run: |
        ${{ runner.os == 'Linux' && '
        sudo apt-get install -y clang clang-21 lld \
                     lld-21 llvm-21-linker-tools' || '' }}
        ${{ steps.cfg.outputs.cross == 'Windows' && '
        sudo apt-get install -y --install-recommends ca-certificates \
                     msitools python3 winbind winehq-staging' || '' }}
        ${{ runner.os == 'macOS' && 'set +e
        brew install coreutils gnu-sed
        printf -vP "$(brew --prefix)/opt/%s/libexec/gnubin:" gnu-sed coreutils
        P="${P}$PATH"
        echo "export PATH=\"$P\"" >> "$HOME/.bash_profile"
        echo "PATH=$P" >> "$GITHUB_ENV"' || '' }}
        ${{ steps.cfg.outputs.wine && 'mkdir -p "$msvc_sdk_dir"
        "$msvc_dir/vsdownload.py" --accept-license --dest "$msvc_sdk_dir"
        "$msvc_dir/install.sh" "$msvc_sdk_dir"' || '' }}

    - name: Get available compilers
      run: |
        set +e
        uname -a
        printf -- '\n+---------+\n|compilers|\n+---------+\n'
        . .github/workflows/functions.bash
        get_compilers
        declare -a cc_clang cc_gcc
        declare -A cc_v
        for _cc in "${compilers[@]}"; do
          v=$("$_cc" --version 2>&1 | head -1)
          case "$_cc" in
          clang*)
            cc_clang+=("$_cc") ;;
          gcc*)
            [[ ! "$v" =~ clang ]] || continue
            cc_gcc+=("$_cc") ;;
          esac
          cc_v["$_cc"]="$v"
        done
        n=$(printf '%s\n' "${cc_v[@]}" | wc -L)
        for _cc in "${cc_clang[@]}"; do
          printf "%-${n}s\t%s\n" "${cc_v[$_cc]}" "$_cc"
        done | tee compilers_clang
        for _cc in "${cc_gcc[@]}"; do
          printf "%-${n}s\t%s\n" "${cc_v[$_cc]}" "$_cc"
        done | tee compilers_gcc

    - name: Compile
      working-directory: ${{ github.workspace }}/src
      env:
        build_dir: ${{ steps.env.outputs.build_dir }}
        built_exe: ${{ steps.env.outputs.built_exe }}
        built_exe2: ${{ steps.env.outputs.built_exe2 }}
        msvc_dir: ${{ steps.env.outputs.msvc_dir }}
        msvc_bin_dir: ${{ steps.env.outputs.msvc_bin_dir }}
        sources: args.c dbs26.c
      run: |
        mkdir -p "$build_dir"
        ${{ steps.cfg.outputs.native == 'Linux' && '"$__cc" $__cflags -o "$built_exe" $sources
        strip --strip-all "$built_exe"' || '' }}
        ${{ steps.cfg.outputs.cross == 'Windows' && 'BIN="$msvc_bin_dir" . "$msvc_dir/msvcenv-native.sh"
        "$__cc" --target=x86_64-windows-msvc $__cflags -o "$built_exe" $sources
        export PATH="$msvc_bin_dir:$PATH"
        cl /nologo /TC /std:clatest /experimental:c11atomics /DNDEBUG=1 /Wall /O2 /Oi /GL /GF /Zo- /favor:AMD64 /arch:AVX2 /MT /Fe: "$built_exe2" $sources' || '' }}
        ${{ steps.cfg.outputs.native == 'macOS' && '"$__cc" -arch arm64 $__cflags -o "$built_exe-arm64" $sources
        "$__cc" -arch x86_64 $__cflags -o "$built_exe-x86_64" $sources
        lipo -create -output "$built_exe" "$built_exe-arm64" "$built_exe-x86_64"' || '' }}

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.cfg.outputs.zip }}
        path: |
          ${{ steps.env.outputs.built_exe }}
          ${{ steps.env.outputs.built_exe2 }}
          LICENSE
          README.md

    - name: Verify binary output
      working-directory: ${{ steps.env.outputs.build_dir }}
      env:
        Linux: |
          ${{ matrix.os == 'Linux' && 'try ./' || '' }}${{ matrix.os == 'Linux' && steps.cfg.outputs.exe || '' }}
        macOS: |
          ${{ matrix.os == 'macOS' && 'try arch -arm64 ./' || '' }}${{ matrix.os == 'macOS' && steps.cfg.outputs.exe || '' }}
          ${{ matrix.os == 'macOS' && 'try arch -x86_64 ./' || '' }}${{ matrix.os == 'macOS' && steps.cfg.outputs.exe || '' }}
        Windows: |
          ${{ matrix.os == 'Windows' && 'try ./' || '' }}${{ matrix.os == 'Windows' && steps.cfg.outputs.exe || '' }}
          ${{ matrix.os == 'Windows' && 'try ./' || '' }}${{ matrix.os == 'Windows' && steps.cfg.outputs.exe2 || '' }}
      run: |
        try() {
          local f="$RUNNER_TEMP/test.bin"
          ${{ steps.cfg.outputs.wine }}"$@" -o -   | sha1sum     ; rm -f "$f"
          ${{ steps.cfg.outputs.wine }}"$@" -o "$f"; sha1sum "$f"; rm -f "$f"
        }
        ${{ matrix.os == 'Linux' && env.Linux || '' }}
        ${{ matrix.os == 'macOS' && env.macOS || '' }}
        ${{ matrix.os == 'Windows' && env.Windows || '' }}
