name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    shell: bash

env:
  __c_src: args.c dbs26.c
  __executable: dbs26
  __exec_prefix: ./
  __build_path: build
  __dest_path: dest
  __src_path: src
  __nproc: nproc
  __cc: clang-21
  __cflags: -std=gnu23 -flto=full -fuse-ld=lld -O3 -Wall -Wextra -Wpedantic -Weverything -DNDEBUG=1 -march=x86-64-v3 -mtune=znver3

jobs:
  build:
    name: ${{ matrix.os }}${{ matrix.os != matrix.on && ' target on ' || '' }}${{ matrix.os != matrix.on && matrix.on || '' }}
    runs-on: ${{ matrix.on == 'macOS' && 'macos-15' || 'ubuntu-24.04' }}
    strategy:
      matrix:
        os: [ Linux, macOS, Windows ]
        include:
          - os: Linux
            on: Linux
          - os: macOS
            on: macOS
          - os: Windows
            on: Linux
    steps:
    - name: Set build config
      id: cfg
      env:
        cross: ${{ matrix.os != runner.os && matrix.os || '' }}
        native: ${{ matrix.os == runner.os && runner.os || '' }}
        suffix: ${{ matrix.os == 'Windows' && '.exe' || '' }}
        exe1: ${{ env.__executable }}${{ env.suffix }}
        exe2: ${{ matrix.os == 'Windows' && 'cl-' || '' }}${{ env.__executable }}${{ env.suffix }}
        wine: ${{ matrix.os == 'Windows' && runner.os != 'Windows' && 'WINEDEBUG=-all wine64 ' || '' }}
        zip: dbs26-${{ matrix.os }}
      run: |
        printf '%s=%s\n' \
               exe1 "$exe1" \
               exe2 "$exe2" \
               native "$native" \
               cross "$cross" \
               suffix "$suffix" \
               wine "$wine" \
               zip "$zip" >> "$GITHUB_OUTPUT"
    - name: Install system updates
      env:
        Linux: |
          ${{ matrix.os == 'Windows' && 'sudo mkdir -pm755 /etc/apt/keyrings
          wget -qO- https://dl.winehq.org/wine-builds/winehq.key | \
          sudo gpg --dearmor -o /etc/apt/keyrings/winehq-archive.key -
          wget -qO- https://dl.winehq.org/wine-builds/ubuntu/dists/noble/winehq-noble.sources | \
          sudo tee /etc/apt/sources.list.d/winehq.sources
          sudo dpkg --add-architecture i386' || '' }}
          echo "deb http://apt.llvm.org/noble/ llvm-toolchain-noble main" | \
          sudo tee /etc/apt/sources.list.d/apt.llvm.org.list
          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | \
          sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
          sudo apt-get update
          sudo apt-get upgrade -y
        macOS: |
          set +e
          brew update
          brew upgrade
          brew install bash
      run: |
        ${{ runner.os == 'Linux' && env.Linux || '' }}
        ${{ runner.os == 'macOS' && env.macOS || '' }}
    - name: Set env variables
      env:
        __msvc_path_Linux: ${{ matrix.os == 'Windows' && 'msvc' || '' }}
        __exec_prefix_Linux: ${{ matrix.os == 'Windows' && 'WINEDEBUG=-all wine64 ' || '' }}./
        __exec_prefix_macOS: 'arch -'
        __nproc_macOS: sysctl -n hw.logicalcpu
        __cc_macOS: clang
        __cflags_macOS: -std=gnu2x -flto=full -O3 -Wall -Wextra -Wpedantic -Weverything -DNDEBUG=1
      run: |
        def() {
          set "$1" "${1}_${{ runner.os }}"
          if [[ "${!2}" ]]; then
            declare -g "$1=${!2//$'\n'/ }"
            echo "$1=${!1}" >> "$GITHUB_ENV"
          fi
        }

        def __cc
        def __cflags
        def __nproc
        ${{ steps.cfg.outputs.wine && 'def __msvc_path
        [[ "$__msvc_sdk_path" ]] || {
          __msvc_sdk_path="$__msvc_path/sdk"
          echo "__msvc_sdk_path=$__msvc_sdk_path" >> "$GITHUB_ENV"
        }
        [[ "$__msvc_dir" ]] || {
          __msvc_dir="$GITHUB_WORKSPACE/$__msvc_path"
          echo "__msvc_dir=$__msvc_dir" >> "$GITHUB_ENV"
        }
        [[ "$__msvc_sdk_dir" ]] || {
          __msvc_sdk_dir="$__msvc_dir/sdk"
          echo "__msvc_sdk_dir=$__msvc_sdk_dir" >> "$GITHUB_ENV"
        }' || '' }}
        [[ "$__build_dir" ]] || {
          __build_dir="$GITHUB_WORKSPACE/$__build_path"
          echo "__build_dir=$__build_dir" >> "$GITHUB_ENV"
        }
        echo "__exe=$__build_dir/$__executable" >> "$GITHUB_ENV"

    - uses: actions/checkout@v4

    - name: Clone msvc-wine
      if: ${{ steps.cfg.outputs.wine }}
      uses: actions/checkout@v4
      with:
        repository: mstorsjo/msvc-wine
        path: ${{ env.__msvc_dir }}
        ref: master

    - name: Install build dependencies
      run: |
        ${{ runner.os == 'Linux' && '
        sudo apt-get install -y clang clang-21 lld \
                     lld-21 llvm-21-linker-tools' || '' }}
        ${{ steps.cfg.outputs.cross == 'Windows' && '
        sudo apt-get install -y --install-recommends ca-certificates \
                     msitools python3 winbind winehq-staging' || '' }}
        ${{ runner.os == 'macOS' && 'set +e
        brew install coreutils gnu-sed
        printf -vP "$(brew --prefix)/opt/%s/libexec/gnubin:" gnu-sed coreutils
        P="${P}$PATH"
        echo "export PATH=\"$P\"" >> "$HOME/.bash_profile"
        echo "PATH=$P" >> "$GITHUB_ENV"' || '' }}
        ${{ steps.cfg.outputs.wine && 'mkdir -p "$__msvc_sdk_dir"
        "$__msvc_dir/vsdownload.py" --accept-license --dest "$__msvc_sdk_dir"
        "$__msvc_dir/install.sh" "$__msvc_sdk_dir"
        echo "PATH=$__msvc_sdk_dir/bin/x64:$PATH" >> "$GITHUB_ENV"' || '' }}

    - name: Get available compilers
      run: |
        set +e
        uname -a
        printf -- '\n+---------+\n|compilers|\n+---------+\n'
        . .github/workflows/functions.bash
        get_compilers
        declare -a cc_clang cc_gcc
        declare -A cc_v
        for _cc in "${compilers[@]}"; do
          v=$("$_cc" --version 2>&1 | head -1)
          case "$_cc" in
          clang*)
            cc_clang+=("$_cc") ;;
          gcc*)
            [[ ! "$v" =~ clang ]] || continue
            cc_gcc+=("$_cc") ;;
          esac
          cc_v["$_cc"]="$v"
        done
        n=$(printf '%s\n' "${cc_v[@]}" | wc -L)
        for _cc in "${cc_clang[@]}"; do
          printf "%-${n}s\t%s\n" "${cc_v[$_cc]}" "$_cc"
        done | tee compilers_clang
        for _cc in "${cc_gcc[@]}"; do
          printf "%-${n}s\t%s\n" "${cc_v[$_cc]}" "$_cc"
        done | tee compilers_gcc

    - name: Compile
      working-directory: ${{ github.workspace }}/${{ env.__src_path }}
      run: |
        mkdir -p "$__build_dir"
        ${{ steps.cfg.outputs.native == 'Linux' && '"$__cc" $__cflags -o "$__exe" $__c_src
        strip --strip-all "$__exe"' || '' }}
        ${{ steps.cfg.outputs.cross == 'Windows' && 'BIN="$__msvc_sdk_dir/bin/x64" . "$__msvc_dir/msvcenv-native.sh"
        "$__cc" --target=x86_64-windows-msvc $__cflags -o "$__exe" $__c_src
        cl /nologo /TC /std:clatest /experimental:c11atomics /DNDEBUG=1 /Wall /O2 /Oi /GL /GF /Zo- /favor:AMD64 /arch:AVX2 /MT /Fe: "cl-$__executable" $__c_src' || '' }}
        ${{ steps.cfg.outputs.native == 'macOS' && '"$__cc" -arch arm64 $__cflags -o "$__exe-arm64" $__c_src
        "$__cc" -arch x86_64 $__cflags -o "$__exe-x86_64" $__c_src
        lipo -create -output "$__exe" "$__exe-arm64" "$__exe-x86_64"' || '' }}

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.cfg.outputs.zip }}
        path: |
          ${{ matrix.os == 'Windows' && 'cl-' || '' }}${{ env.__executable }}
          ${{ matrix.os == 'Windows' && env.__executable || '' }}
          LICENSE
          README.md

    - name: Verify binary output
      working-directory: ${{ env.__build_dir }}
      env:
        try1: try ${{ steps.cfg.outputs.native == 'macOS' && 'arch -arm64 ' || '' }}"./${{ steps.cfg.outputs.exe1 }}"
        try2: try ${{ steps.cfg.outputs.native == 'macOS' && 'arch -x86_64 ' || '' }}"./${{ steps.cfg.outputs.exe2 }}"
      run: |
        try() {
          local f="$RUNNER_TEMP/test.bin"
          ${{ steps.cfg.outputs.wine }}"$@" -o -   | sha1sum     ; rm -f "$f"
          ${{ steps.cfg.outputs.wine }}"$@" -o "$f"; sha1sum "$f"; rm -f "$f"
        }
        ${{ env.try1 }}
        ${{ matrix.os != 'Linux' && env.try2 || '' }}
