name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-ubuntu-24_04:
    runs-on: ubuntu-24.04
    steps:
    - name: Add apt.llvm.org
      run: |
        printf -- 'deb http://apt.llvm.org/noble/ llvm-toolchain-noble%s main\n' '' '-20' | sudo tee /etc/apt/sources.list.d/apt.llvm.org.list
        wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc

    - name: Upgrade packages
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y

    - name: Upgrade Clang
      run: |
        sudo apt-get install clang clang-20 lld lld-20 llvm-20-linker-tools || true

    - name: Add dl.winehq.org
      run: |
        sudo dpkg --add-architecture i386
        sudo mkdir -pm755 /etc/apt/keyrings
        wget -qO - https://dl.winehq.org/wine-builds/winehq.key | sudo gpg --dearmor -o /etc/apt/keyrings/winehq-archive.key -
        sudo wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/noble/winehq-noble.sources

    - name: Install Windows build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --install-recommends ca-certificates msitools python3 winbind winehq-staging

    - uses: actions/checkout@v4

    - name: Clone msvc-wine
      uses: actions/checkout@v4
      with:
        repository: mstorsjo/msvc-wine
        path: msvc
        ref: master

    - name: Set environment
      shell: bash
      run: |
        mkdir -p build
        mkdir -p msvc/sdk
        __cflags=(         \
          -std=gnu23       \
          -O3              \
          -flto=full       \
          -march=x86-64-v3 \
          -mtune=znver3    \
          -Wall            \
          -Wextra          \
          -Wpedantic       \
          -Weverything     \
          -DNDEBUG=1       \
        )
        echo "__cflags=${__cflags[@]}" >> "$GITHUB_ENV"
        echo "__srcdir=$(realpath -e src)" >> "$GITHUB_ENV"
        echo "__winsdk=$(realpath -e msvc/sdk)" >> "$GITHUB_ENV"
        echo "ncpu=$((n = $(nproc)+0, n > 0 ? n : 1))" >> "$GITHUB_ENV"

    - name: Get available compilers
      shell: bash
      run: |
        set +e
        uname -a
        printf -- '\n+---------+\n|compilers|\n+---------+\n'
        . scripts/lib.sh
        get_compilers
        declare -a cc_clang cc_gcc
        declare -A cc_v
        for _cc in "${compilers[@]}"; do
          v=$("$_cc" --version 2>&1 | head -1)
          case "$_cc" in
          clang*)
            cc_clang+=("$_cc") ;;
          gcc*)
            [[ ! "$v" =~ clang ]] || continue
            cc_gcc+=("$_cc") ;;
          esac
          cc_v["$_cc"]="$v"
        done
        n=$(printf '%s\n' "${cc_v[@]}" | wc -L)
        for _cc in "${cc_clang[@]}"; do
          printf "%-${n}s\t%s\n" "${cc_v[$_cc]}" "$_cc"
        done | tee compilers_clang
        for _cc in "${cc_gcc[@]}"; do
          printf "%-${n}s\t%s\n" "${cc_v[$_cc]}" "$_cc"
        done | tee compilers_gcc

    - name: Compile for Linux
      shell: bash
      run: |
        clang-20 -working-directory "$__srcdir" $__cflags \
                 dbs26.c -o ../build/dbs26
        strip --strip-all build/dbs26

    - name: Archive Linux binary
      uses: actions/upload-artifact@v4
      with:
        name: dbs26-linux
        path: |
          build/dbs26
          LICENSE
          README.md

    - name: Install Windows SDK
      shell: bash
      run: |
        msvc/vsdownload.py --accept-license --dest "$__winsdk"
        msvc/install.sh "$__winsdk"

    - name: Compile for Windows
      shell: bash
      run: |
        BIN="$__winsdk/bin/x64" . msvc/msvcenv-native.sh
        clang-20 -working-directory "$__srcdir" $__cflags \
                 --target=x86_64-windows-msvc -fuse-ld=lld \
                 dbs26.c -o ../build/dbs26.exe

    - name: Archive Windows binary
      uses: actions/upload-artifact@v4
      with:
        name: dbs26-windows
        path: |
          build/dbs26.exe
          LICENSE
          README.md

    - name: Verify Linux binary output
      shell: bash
      run: build/dbs26 -o- | sha1sum

    - name: Verify Windows binary output
      shell: bash
      run: WINEDEBUG=-all wine64 build/dbs26.exe -o- | sha1sum

  build-macos-15:
    runs-on: macos-15
    steps:
    - name: Install updates
      run: |
        set +e
        echo "bash $BASH_VERSION"
        brew update
        brew upgrade
        brew install bash

    - name: Install dependencies
      run: |
        set +e
        echo "bash $BASH_VERSION"
        brew install binutils coreutils gnu-sed make
        if [[ -z "$HOMEBREW_PREFIX" ]]; then
          export HOMEBREW_PREFIX="$(brew --prefix)"
          echo 'export HOMEBREW_PREFIX="$(brew --prefix)"' >> "$HOME/.bash_profile"
          echo "HOMEBREW_PREFIX=$HOMEBREW_PREFIX" >> "$GITHUB_ENV"
        fi
        export PATH="$(brew --prefix binutils)/bin:$HOMEBREW_PREFIX/opt/coreutils/libexec/gnubin:$HOMEBREW_PREFIX/opt/gnu-sed/libexec/gnubin:$HOMEBREW_PREFIX/opt/make/libexec/gnubin:$PATH"
        printf '%s\n' "alias nproc='sysctl -n hw.logicalcpu'" \
               "export PATH=\"$PATH\"" >> "$HOME/.bash_profile"
        printf '%s\n' "PATH=$PATH" \
               "ncpu=$(sysctl -n hw.logicalcpu)" >> "$GITHUB_ENV"

    - uses: actions/checkout@v4

    - name: Get available compilers
      shell: bash
      run: |
        set +e
        uname -a
        printf -- '\n+---------+\n|compilers|\n+---------+\n'
        . scripts/lib.sh
        get_compilers
        declare -a cc_clang cc_gcc
        declare -A cc_v
        for _cc in "${compilers[@]}"; do
          v=$("$_cc" --version 2>&1 | head -1)
          case "$_cc" in
          clang*)
            cc_clang+=("$_cc") ;;
          gcc*)
            [[ ! "$v" =~ clang ]] || continue
            cc_gcc+=("$_cc") ;;
          esac
          cc_v["$_cc"]="$v"
        done
        n=$(printf '%s\n' "${cc_v[@]}" | wc -L)
        for _cc in "${cc_clang[@]}"; do
          printf "%-${n}s\t%s\n" "${cc_v[$_cc]}" "$_cc"
        done | tee compilers_clang
        for _cc in "${cc_gcc[@]}"; do
          printf "%-${n}s\t%s\n" "${cc_v[$_cc]}" "$_cc"
        done | tee compilers_gcc

    - name: Compile for macOS
      shell: bash
      run: |
        mkdir -p build
        pushd src
        F=(-std=gnu2x -O3 -flto=full -Wall -Wextra -Wpedantic -Weverything -DNDEBUG=1)
        clang -arch arm64 "${F[@]}" -o ../build/dbs26-arm64 dbs26.c
        clang -arch x86_64 "${F[@]}" -o ../build/dbs26-x86_64 dbs26.c
        popd
        pushd build
        lipo -create -output dbs26 dbs26-arm64 dbs26-x86_64
        popd

    - name: Archive macOS binary
      uses: actions/upload-artifact@v4
      with:
        name: dbs26-macos
        path: |
          build/dbs26
          LICENSE
          README.md

    - name: Verify macOS binary output
      run: |
        arch -arm64 build/dbs26 -o- | sha1sum
        arch -x86_64 build/dbs26 -o- | sha1sum
