name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: ${{ matrix.os }} target on ${{ matrix.on }}
    runs-on: ${{ matrix.on }}
    strategy:
      fail-fast: false
      matrix:
        os: [ Linux, macOS, Windows ]
        on: [ ubuntu-24.04, macos-15, macos-14 ]
        exclude:
          - os: Linux
            on: macos-15
          - os: Linux
            on: macos-14
          - os: macOS
            on: ubuntu-24.04
    steps:
    - name: id
      id: id
      env:
        os_: ${{ matrix.os }}_
        _for_: ${{ matrix.os != runner.os && '_for_' || '' }}${{ matrix.os != runner.os && matrix.os || '' }}
        on_: ${{ matrix.os != runner.os && 'on_' || '' }}${{ matrix.os != runner.os && runner.os || '' }}
        _on_: ${{ matrix.os != runner.os && '=on_' || '' }}${{ matrix.os != runner.os && runner.os || '' }}
        type: ${{ matrix.os == runner.os && 'native' || 'cross' }}
        on_for: f="${x}_on_${{ runner.os }}_for_${{ matrix.os }}"; y="${!f}"; [[ -z "${y// /}" ]] || { echo "$f"; continue; }
      run: |
        methods() {
          local x f y
          for x in "pre_$1" "$1" "post_$1"; do
            ${{ matrix.os != runner.os && env.on_for || '' }}
            f="${x}_${{ env.type }}_${{ matrix.os }}"; y="${!f}"; [[ -z "${y// /}" ]] || { echo "$f"; continue; }
            f="${x}_${{ env.type }}"; y="${!f}"; [[ -z "${y// /}" ]] || { echo "$f"; continue; }
            f="${x}_on_${{ runner.os }}"; y="${!f}"; [[ -z "${y// /}" ]] || { echo "$f"; continue; }
            y="${!x}"; [[ -z "${y// /}" ]] || echo "$x"
          done
        }
        __methods="$(declare -f methods)"
        if (( BASH_VERSINFO == 3 )); then
          __methods=$(printf 'eval %q' "$__methods")
        fi
        {
          echo 'update_methods<<EOF'
          echo "$__methods"
          echo 'methods update'
          echo 'EOF'
        } >> "$GITHUB_OUTPUT"
        {
          echo 'depends_methods<<EOF'
          echo "$__methods"
          echo 'methods depends'
          echo 'EOF'
        } >> "$GITHUB_OUTPUT"
        {
          echo 'compile_methods<<EOF'
          echo "$__methods"
          echo 'methods compile'
          echo 'EOF'
        } >> "$GITHUB_OUTPUT"
        {
          echo 'validate_methods<<EOF'
          echo "$__methods"
          echo 'methods validate'
          echo 'EOF'
        } >> "$GITHUB_OUTPUT"

        printf '%s\n' \
               "on_${{ runner.os }}=on_${{ runner.os }}" \
               "for_${{ matrix.os }}=for_${{ matrix.os }}" \
               ${{ env.on_ }}${{ env._for_ }}${{ env._on_ }}${{ env._for_ }} \
               "build=${{ matrix.os != runner.os && env.os_ || '' }}${{ matrix.on }}" \
               "${{ matrix.os }}_${{ runner.os }}=${{ env.type }}_${{ matrix.os }}" \
               "${{ env.type }}_${{ matrix.os }}=${{ env.type }}_${{ matrix.os }}" \
               "${{ env.type }}=${{ env.type }}" >> "$GITHUB_OUTPUT"
    - name: Set build params
      id: cfg
      env:
        cc: ${{ steps.id.outputs.on_macOS && 'clang' || 'clang-21' }}
        cl: ${{ steps.id.outputs.for_Windows && 'cl' || '' }}
        ccl: ${{ steps.id.outputs.on_Linux_for_Windows && 'clang-cl-21' || '' }}
        baseflags: -std=gnu2${{ steps.id.outputs.on_macOS && 'x' || '3' }} -flto=full -O3 -Wall -Wextra -Wpedantic -Weverything -DNDEBUG=1
        archflags: ${{ ! steps.id.outputs.for_macOS && ' -fuse-ld=lld' || '' }}${{ steps.id.outputs.for_Linux && ' -march=x86-64-v3 -mtune=znver3' || '' }}
        ext: ${{ steps.id.outputs.for_Windows && '.exe' || '' }}
      run: |
        printf '%s\n' \
               cc=${{ env.cc }} ${{ env.cl && 'cl=' || '' }}${{ env.cl }} ${{ env.ccl && 'ccl=' || '' }}${{ env.ccl }} \
               cflags="${{ env.baseflags }}${{ env.archflags }}" \
               exe=dbs26-${{ env.cc }}${{ env.ext }} \
               ${{ env.cl && 'exe_cl=dbs26-' || '' }}${{ env.cl }}${{ env.cl && env.ext || '' }} \
               ${{ env.ccl && 'exe_ccl=dbs26-' || '' }}${{ env.ccl }}${{ env.ccl && env.ext || '' }} \
               pkg=dbs26-${{ steps.id.outputs.build }} \
               src="args.c dbs26.c" >> "$GITHUB_OUTPUT"
    - name: Update system packages
      env:
        pre_update_on_Linux_for_Windows: |
          ${{ steps.id.outputs.on_Linux_for_Windows && 'sudo mkdir -pm755 /etc/apt/keyrings
          wget -qO- https://dl.winehq.org/wine-builds/winehq.key | \
          sudo gpg --dearmor -o /etc/apt/keyrings/winehq-archive.key -
          wget -qO- https://dl.winehq.org/wine-builds/ubuntu/dists/noble/winehq-noble.sources | \
          sudo tee /etc/apt/sources.list.d/winehq.sources
          sudo dpkg --add-architecture i386' || '' }}
        update_on_Linux: |
          ${{ steps.id.outputs.on_Linux && '
          echo "deb http://apt.llvm.org/noble/ llvm-toolchain-noble main" | \
          sudo tee /etc/apt/sources.list.d/apt.llvm.org.list
          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | \
          sudo tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
          sudo apt-get update
          sudo apt-get upgrade -y' || '' }}
        update_on_macOS: |
          ${{ steps.id.outputs.on_macOS && 'set +e
          brew update
          brew upgrade
          brew install bash' || '' }}
      run: |
        ${{ steps.id.outputs.update_methods }}
        ${{ steps.id.outputs.on_Linux_for_Windows && env.pre_update_on_Linux_for_Windows || '' }}
        ${{ env.update_on_Linux || '' }}${{ env.update_on_macOS || '' }}
    - name: Set env variables
      id: env
      run: |
        ${{ steps.id.outputs.cross_Windows && '
        [[ "$msvc_path" ]] || msvc_path="msvc"
        [[ "$msvc_dir"  ]] || msvc_dir="$GITHUB_WORKSPACE/$msvc_path"
        [[ "$msvc_sdk"  ]] || msvc_sdk="$msvc_dir/sdk"
        printf "%s=%s\n" \
               msvc_dir "$msvc_dir" \
               msvc_sdk "$msvc_sdk" \
               msvc_bin "$msvc_sdk/bin/x64" >> "$GITHUB_OUTPUT"
        ' || '' }}
        [[ "$build_dir" ]] || build_dir="$GITHUB_WORKSPACE/build"
        printf "%s=%s\n" \
               build_dir "$build_dir" \
               artifacts "$build_dir/${{ steps.cfg.outputs.exe }}${{ steps.cfg.outputs.exe_cl && ' $build_dir/' || '' }}${{ steps.cfg.outputs.exe_cl }}${{ steps.cfg.outputs.exe_ccl && ' $build_dir/' || '' }}${{ steps.cfg.outputs.exe_ccl }}" >> "$GITHUB_OUTPUT"

    - uses: actions/checkout@v4

    - name: Clone msvc-wine
      if: ${{ steps.id.outputs.cross_Windows }}
      uses: actions/checkout@v4
      with:
        repository: mstorsjo/msvc-wine
        path: ${{ steps.env.outputs.msvc_dir }}
        ref: master

    - name: Install dependencies
      env:
        msvc_dir: ${{ steps.env.outputs.msvc_dir }}
        msvc_sdk: ${{ steps.env.outputs.msvc_sdk }}
      run: |
        ${{ steps.id.outputs.depends_methods }}

        ${{ steps.id.outputs.on_Linux && 'sudo apt-get install -y clang clang-21 lld lld-21 llvm-21-linker-tools' || '' }}
        ${{ steps.id.outputs.on_Linux_for_Windows && 'sudo apt-get install -y ca-certificates msitools python3 winbind winehq-staging' || '' }}

        ${{ steps.id.outputs.on_macOS && 'set +e' || '' }}
        ${{ steps.id.outputs.on_macOS_for_Windows && 'brew install msitools wine@staging' || '' }}

        ${{ steps.id.outputs.cross_Windows && 'mkdir -p "$msvc_sdk"' || '' }}
        ${{ steps.id.outputs.cross_Windows && '"$msvc_dir/vsdownload.py" --accept-license --dest "$msvc_sdk"' || '' }}
        ${{ steps.id.outputs.cross_Windows && '"$msvc_dir/install.sh" "$msvc_sdk"' || '' }}

        ${{ steps.id.outputs.on_macOS && 'brew install coreutils gnu-sed' || '' }}
        ${{ steps.id.outputs.on_macOS_for_Windows && 'brew install llvm lld binutils' || '' }}
        ${{ steps.id.outputs.on_macOS && 'PFX="$(brew --prefix)"' || '' }}
        ${{ steps.id.outputs.on_macOS && 'PATH="$PFX/opt/coreutils/libexec/gnubin:$PFX/opt/gnu-sed/libexec/gnubin:$PATH"' || '' }}
        ${{ steps.id.outputs.on_macOS_for_Windows && 'PATH="$PFX/opt/llvm/bin:$PFX/opt/binutils/bin:$PATH"' || '' }}
        ${{ steps.id.outputs.on_macOS && 'echo "$PATH" >> "$GITHUB_PATH"' || '' }}

    - name: Introspect compilers
      run: |
        set +e
        uname -a
        printf -- '\n+---------+\n|compilers|\n+---------+\n'
        . .github/workflows/functions.bash
        get_compilers
        declare -a cc_clang cc_gcc
        declare -A cc_v
        for _cc in "${compilers[@]}"; do
          v=$("$_cc" --version 2>&1 | head -1)
          case "$_cc" in
          clang*)
            cc_clang+=("$_cc") ;;
          gcc*)
            [[ ! "$v" =~ clang ]] || continue
            cc_gcc+=("$_cc") ;;
          esac
          cc_v["$_cc"]="$v"
        done
        n=$(printf '%s\n' "${cc_v[@]}" | wc -L)
        for _cc in "${cc_clang[@]}"; do
          printf "%-${n}s\t%s\n" "${cc_v[$_cc]}" "$_cc"
        done | tee compilers_clang
        for _cc in "${cc_gcc[@]}"; do
          printf "%-${n}s\t%s\n" "${cc_v[$_cc]}" "$_cc"
        done | tee compilers_gcc

    - name: Compile
      working-directory: ${{ github.workspace }}/src
      env:
        build_dir: ${{ steps.env.outputs.build_dir }}
        compile_native_Linux: |
          "${{ steps.cfg.outputs.cc }}" ${{ steps.cfg.outputs.cflags }} -o "$build_dir/${{ steps.cfg.outputs.exe }}" ${{ steps.cfg.outputs.src }}
          strip --strip-all "$build_dir/${{ steps.cfg.outputs.exe }}"
        compile_native_macOS: |
          "${{ steps.cfg.outputs.cc }}" -arch arm64 ${{ steps.cfg.outputs.cflags }} -o "$build_dir/${{ steps.cfg.outputs.exe }}-arm64" ${{ steps.cfg.outputs.src }}
          "${{ steps.cfg.outputs.cc }}" -arch x86_64 ${{ steps.cfg.outputs.cflags }} -o "$build_dir/${{ steps.cfg.outputs.exe }}-x86_64" ${{ steps.cfg.outputs.src }}
          lipo -create -output "$build_dir/${{ steps.cfg.outputs.exe }}" "$build_dir/${{ steps.cfg.outputs.exe }}-arm64" "$build_dir/${{ steps.cfg.outputs.exe }}-x86_64"
        compile_cross_Windows: |
          BIN="${{ steps.env.outputs.msvc_bin }}" . "${{ steps.env.outputs.msvc_dir }}/msvcenv-native.sh"
          export PATH="${{ steps.env.outputs.msvc_bin }}:$PATH"
          echo "\"${{ steps.cfg.outputs.cc }}\" --target=$TARGET_TRIPLE ${{ steps.cfg.outputs.cflags }} -o \"$build_dir/${{ steps.cfg.outputs.exe }}\" ${{ steps.cfg.outputs.src }}"
          "${{ steps.cfg.outputs.cc }}" --target=$TARGET_TRIPLE ${{ steps.cfg.outputs.cflags }} -o "$build_dir/${{ steps.cfg.outputs.exe }}" ${{ steps.cfg.outputs.src }}
          echo "\"${{ steps.cfg.outputs.cl }}\" /TC /std:clatest /experimental:c11atomics /DNDEBUG=1 /Wall /O2 /Oi /GL /GF /Zo- /MT /Fe: \"$build_dir/${{ steps.cfg.outputs.exe_cl }}\" ${{ steps.cfg.outputs.src }}"
          "${{ steps.cfg.outputs.cl }}" /TC /std:clatest /experimental:c11atomics /DNDEBUG=1 /Wall /O2 /Oi /GL /GF /Zo- /MT /Fe: "$build_dir/${{ steps.cfg.outputs.exe_cl }}" ${{ steps.cfg.outputs.src }}
        post_compile_on_Linux_for_Windows: |
          echo "\"${{ steps.cfg.outputs.ccl }}\" /TC /DNDEBUG=1 /Wall /O2 /Oi /GF /Zo- /MT /Fe: \"$build_dir/${{ steps.cfg.outputs.exe_ccl }}\" -fuse-ld=lld ${{ steps.cfg.outputs.src }}"
          "${{ steps.cfg.outputs.ccl }}" /TC /DNDEBUG=1 /Wall /O2 /Oi /GF /Zo- /MT /Fe: "$build_dir/${{ steps.cfg.outputs.exe_ccl }}" -fuse-ld=lld ${{ steps.cfg.outputs.src }}
      run: |
        ${{ steps.id.outputs.compile_methods }}
        mkdir -p "$build_dir"
        ${{ steps.id.outputs.native_Linux && env.compile_native_Linux || '' }}
        ${{ steps.id.outputs.native_macOS && env.compile_native_macOS || '' }}
        ${{ steps.id.outputs.cross_Windows && env.compile_cross_Windows || '' }}
        ${{ steps.id.outputs.on_Linux_for_Windows && env.post_compile_on_Linux_for_Windows || '' }}

    - name: Package
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.cfg.outputs.pkg }}
        path: |
          ${{ steps.env.outputs.artifacts }}
          LICENSE
          README.md

    - name: Validate
      working-directory: ${{ steps.env.outputs.build_dir }}
      env:
        pre: pre_validate_${{ steps.id.outputs.on_macOS_for_Windows || steps.id.outputs.on_Linux_for_Windows || steps.id.outputs.cross_Windows || steps.id.outputs.cross_Windows || steps.id.outputs.native || '' }}
        out: ${{ runner.temp }}/test.bin
        pre_validate_on_macOS_for_Windows: |
          ${{ steps.id.outputs.on_macOS_for_Windows && 'try() {
            WINEDEBUG=-all wine "$@" -o -     | sha1sum       ; rm -f "$out"
            WINEDEBUG=-all wine "$@" -o "$out"; sha1sum "$out"; rm -f "$out"
          }' || '' }}
        pre_validate_cross_Windows: |
          ${{ steps.id.outputs.cross_Windows && 'try() {
            WINEDEBUG=-all wine64 "$@" -o -     | sha1sum       ; rm -f "$out"
            WINEDEBUG=-all wine64 "$@" -o "$out"; sha1sum "$out"; rm -f "$out"
          }' || '' }}
        pre_validate_native: |
          ${{ steps.id.outputs.native && 'try() {
            "$@" -o -     | sha1sum       ; rm -f "$out"
            "$@" -o "$out"; sha1sum "$out"; rm -f "$out"
          }' || '' }}
        validate_native_Linux: |
          ${{ steps.id.outputs.native_Linux && 'try ./' || '' }}${{ steps.id.outputs.native_Linux && steps.cfg.outputs.exe || '' }}
        validate_native_macOS: |
          ${{ steps.id.outputs.native_macOS && 'try arch -arm64 ./' || '' }}${{ steps.id.outputs.native_macOS && steps.cfg.outputs.exe || '' }}
          ${{ steps.id.outputs.native_macOS && 'try arch -x86_64 ./' || '' }}${{ steps.id.outputs.native_macOS && steps.cfg.outputs.exe || '' }}
        validate_cross_Windows: |
          ${{ steps.id.outputs.cross_Windows && 'try ./' || '' }}${{ steps.id.outputs.cross_Windows && steps.cfg.outputs.exe || '' }}
          ${{ steps.id.outputs.cross_Windows && 'try ./' || '' }}${{ steps.id.outputs.cross_Windows && steps.cfg.outputs.exe_cl || '' }}
        post_validate_on_Linux_for_Windows: |
          ${{ steps.id.outputs.on_Linux_for_Windows && 'try ./' || '' }}${{ steps.id.outputs.on_Linux_for_Windows && steps.cfg.outputs.exe_ccl || '' }}
      run: |
        ${{ steps.id.outputs.validate_methods }}
        ${{ steps.id.outputs.on_macOS_for_Windows && env.pre_validate_on_macOS_for_Windows || '' }}
        ${{ steps.id.outputs.cross_Windows && env.pre_validate_cross_Windows || '' }}
        ${{ steps.id.outputs.native && env.pre_validate_native || '' }}
        ${{ steps.id.outputs.native_Linux && env.validate_native_Linux || '' }}
        ${{ steps.id.outputs.native_macOS && env.validate_native_macOS || '' }}
        ${{ steps.id.outputs.cross_Windows && env.validate_cross_Windows || '' }}
        ${{ steps.id.outputs.on_Linux_for_Windows && env.post_validate_on_Linux_for_Windows || '' }}
